apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
  - name: container1
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: container2
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
spec:
  containers:
  - name: container3
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: pod4
spec:
  containers:
  - name: container4
    image: nginx
