# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: server.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x0fsdcoreAmfServer\"\x8f\x01\n\rSctplbMessage\x12\x10\n\x08SctplbId\x18\x01 \x01(\t\x12)\n\x07Msgtype\x18\x02 \x01(\x0e\x32\x18.sdcoreAmfServer.msgType\x12\x11\n\tGnbIpAddr\x18\x03 \x01(\t\x12\x12\n\nVerboseMsg\x18\x04 \x01(\t\x12\x0b\n\x03Msg\x18\x05 \x01(\x0c\x12\r\n\x05GnbId\x18\x06 \x01(\t\"\x9d\x01\n\nAmfMessage\x12\r\n\x05\x41mfId\x18\x01 \x01(\t\x12\x12\n\nRedirectId\x18\x02 \x01(\t\x12)\n\x07Msgtype\x18\x03 \x01(\x0e\x32\x18.sdcoreAmfServer.msgType\x12\x11\n\tGnbIpAddr\x18\x04 \x01(\t\x12\r\n\x05GnbId\x18\x05 \x01(\t\x12\x12\n\nVerboseMsg\x18\x06 \x01(\t\x12\x0b\n\x03Msg\x18\x07 \x01(\x0c*l\n\x07msgType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08INIT_MSG\x10\x01\x12\x0b\n\x07GNB_MSG\x10\x02\x12\x0b\n\x07\x41MF_MSG\x10\x03\x12\x10\n\x0cREDIRECT_MSG\x10\x04\x12\x0c\n\x08GNB_DISC\x10\x05\x12\x0c\n\x08GNB_CONN\x10\x06\x32\x61\n\x0bNgapService\x12R\n\rHandleMessage\x12\x1e.sdcoreAmfServer.SctplbMessage\x1a\x1b.sdcoreAmfServer.AmfMessage\"\x00(\x01\x30\x01\x42\x13Z\x11./sdcoreAmfServerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021./sdcoreAmfServer'
  _globals['_MSGTYPE']._serialized_start=339
  _globals['_MSGTYPE']._serialized_end=447
  _globals['_SCTPLBMESSAGE']._serialized_start=34
  _globals['_SCTPLBMESSAGE']._serialized_end=177
  _globals['_AMFMESSAGE']._serialized_start=180
  _globals['_AMFMESSAGE']._serialized_end=337
  _globals['_NGAPSERVICE']._serialized_start=449
  _globals['_NGAPSERVICE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
